### PR TITLE
Added OpenAI pip dependency

### PR DESCRIPTION
**Pull request by trancethehuman**
Problem: installing langchain package doesn't include openai. But it requires it to run any OpenAI processes. This means user using lemonai for the first time will have to pip install openai separately.

image

### CODE REVIEW

**Comment by felixbrock** [comment]
Thanks a lot for pointing that out @trancethehuman! I assume you are working with an OpenAI model? I didn't include this import so far, since to my understanding the import is only required if you are working with OpenAI and that might not be the case for every user. For some users this would mean that we are installing dependencies that are not needed. Hope this makes sense?

Something that is missing though, is the information in the Readme that the used example requires this install since it makes use of one of OpenAI's models. Any chance you could you add this information to the Readme? 🙌

**Comment by trancethehuman** [comment]
Yep absolutely. Can add later today 👍

**Comment by trancethehuman** [comment]
@felixbrock let me know if the wording is right.

**Comment by felixbrock** [comment]
Looks good, thank you 🎉

**Pull request merged**
